# Generated by Django 4.1.1 on 2022-09-27 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('sorting', models.PositiveSmallIntegerField(default=0, verbose_name='Sorting')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Coffee'), (1, 'Tea')], db_index=True, verbose_name='Type product')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['sorting'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('sorting', models.PositiveSmallIntegerField(default=0, verbose_name='Sorting')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('volume', models.FloatField(null=True, verbose_name='Volume')),
                ('is_hit', models.BooleanField(db_index=True, default=False, verbose_name='Is hit')),
                ('is_new', models.BooleanField(db_index=True, default=False, verbose_name='Is new')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='If unchecked, the product will not be displayed', verbose_name='Is active')),
                ('category', models.ManyToManyField(related_name='category_products', to='product.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['sorting'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('sorting', models.PositiveSmallIntegerField(default=0, verbose_name='Sorting')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.product', verbose_name='Product image')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['sorting'],
            },
        ),
    ]
