# Generated by Django 4.1.1 on 2022-10-07 17:43

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]
