# Generated by Django 4.1.1 on 2022-10-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20221007_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Coffee'), (1, 'Tea')], db_index=True, default=1, verbose_name='Type product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Name'),
        ),
    ]
