version: '3.9'
services:
  tea-coffee-db:
    image: postgres:14.5
    env_file:
      - _dockerfiles/db/local.env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgres/data
  app:
    image: tea-coffee-app
    build:
      context: .
      dockerfile: _dockerfiles/app/Dockerfile
    depends_on:
      - tea-coffee-db
    volumes:
      - .:/app/code
    ports:
      - "8000:8000"
    env_file:
      - _dockerfiles/app/local.env
    command: "python ./manage.py runserver 0.0.0.0:8000"
volumes:
  db: